#!/usr/bin/python3

# Used to encrypt files before upload (such as build.log)

import subprocess
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("pub", help="Public Key")
parser.add_argument("input", help="Path to file to encrypt")
parser.add_argument("output", help="Path to encrypted output")
args = parser.parse_args()

try:
    subprocess.check_call(["openssl", "rsautl", "-encrypt", "-pubin", "-inkey", args.pub, "-in", args.input, "-out", args.output])
except:
    raise SystemExit("Encryption failed, verify arguments.")



